### ISSUE TITLE
About this demo

### ISSUE THREAD

**Issue by unsanedingding** [Fransferdy/creaturecreator#1]
Sorry, how to start this demo? I can compile the project at ue5.2,  it's ok.But:
1 ）Which Map do I need to open, or which BP do I need to configure?

**Comment by Fransferdy** [comment]
It only works up to UE 5.1.
You can open any map and add the creature bp to it. Then check the creature bp component source code, it has all the code I wrote for creating the mesh, you could follow it to instead create a mesh based on assimp data.
