### ISSUE TITLE
So...Animation run on GPU?

### ISSUE THREAD

**Issue by unsanedingding** [Fransferdy/creaturecreator#2]
Can I convert them into a skeleton system through C++ at runtime and animate based on this response, effectively reduce the performance overhead? Will these animations run on the GPU?

Thanks again. :-)

**Comment by Fransferdy** [comment]
I have seen one guy use animations directly with the skeletal mesh plugin, I haven't used it that way. I was casting the skeletal mesh to a poseable mesh, which allowed me to control bone position programatically/and blueprints(my idea was to use inverse kinematics).
I think it is possible to do what you described, you would have to "read" the static mesh and convert it to skeletal, then create the bone structure to do your things. But it seems to be a bunch of work to get it done that way.

**Comment by unsanedingding** [comment]
First of all, thanks for your quick reply.
So... if I have a skeletal structure, will these animations run on the GPU? If so, I can use this to increase the frame rate at runtime.
Thanks again .

**Comment by unsanedingding** [comment]
thanks
