### ISSUE TITLE
about  #if WITH_EDITOR in these code

### ISSUE THREAD

**Issue by unsanedingding** [Fransferdy/creaturecreator#3]
I noticed a lot of code using #if WITH_EDITOR. Can this work when the game is packaged and run?
Thank you.

**Comment by Fransferdy** [comment]
It works on packaged game, these (#if WITH_EDITOR) are required to keep the editor from crashing when you instantiate the runtime skeletal meshes. I tested it on packaged game only once, I think you should do your own tests to make sure, I'm not the author of the runtime skeletal mesh plugin, just a contributor who did some bug fixes.
