### ISSUE TITLE
About after use glTFRuntime 

### ISSUE THREAD

**Issue by rtjia** [Fransferdy/creaturecreator#5]
I'm back ;-)

Thank's again.

**Comment by Fransferdy** [comment]
Hi! I'm sorry I wish I could help, but I haven't used glTFRuntime yet, when the time comes, I will try to use it haha, but right now I haven't even cloned their plugin yet. I only read the docs and it seemed active and maintained.

**Comment by unsanedingding** [comment]
你使用过assimp吗？我在使用assimp的时候，贴图就有错误了:-(
